Добавлена модель пользователя, авторизация, данные по 3 пользователям…
Sphere-Ya/backend pull request #13
Opened 2024-04-04 15:16 UTC by Edelveisx

1. Модель юзера
2. Авторизация (Token Based Authentication + djoser)
3. Первоначальная миграции
4. Миграция данных (3 тестовых пользователя)

2024-04-04 21:32 UTC, YaStirayuLaskoy requested changes
В целом, всё круто, но я бы исправил пару моментов

2024-04-04 21:32 UTC, YaStirayuLaskoy commented on sphere_backend/api/serializers_users.py
> +from django.contrib.auth import get_user_model
Хорошая практика добавлять коммент в начале каждого файла, который не генерируется автоматически:
`
"""User serializers."""
`

Зачем?

1. код будут читать еще другие разработчики, это удобно;
2. support от IDE;
3. автогенерация документации;
4. хороший тон;

2024-04-04 21:32 UTC, YaStirayuLaskoy commented on sphere_backend/api/serializers_users.py
> +
По той же причине при объявлении класса описывается, что он должен делать

2024-04-04 21:32 UTC, YaStirayuLaskoy commented on sphere_backend/users/admin.py
> +        'password',
Админ будет видеть все пароли пользователей? Вроде, это не совсем безопасно

2024-04-05 08:52 UTC, ulanovPS approved these changes

2024-04-05 15:34 UTC, YaStirayuLaskoy approved these changes
Мне всё нравится

2024-04-05 17:55 UTC, merged